### ISSUE TITLE
Crash in timer

### ISSUE THREAD

**Issue by murphy360** [murphy360/discord-bot-everything#13]
/home/ubuntu/discordbot/discord-bot-everything/commands/trivia.js:78
                        const progressText = '▇'.repeat(progress);
                                                 ^

RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at getBar (/home/ubuntu/discordbot/discord-bot-everything/commands/trivia.js:78:29)
    at Timeout.pBar [as _onTimeout] (/home/ubuntu/discordbot/discord-bot-everything/commands/trivia.js:61:28)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:492:7)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by cgacord** [comment]
I think this is caused by errors else where in the code.
